### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by damons** [roboticslab-cseiitg/ProjectTartarus#1]
Hi,

I really like the work done here, and I'm interested in using it for my own autonomous agents.  Is this project still active?  Are there issues being tracked somewhere?

It's big enough that it requires true project tracking, and I'm wondering if I'm missing out.

Yours faithfully,
Damon

**Comment by divyadk** [comment]
Hi, Thanks for your interest. We are actively maintaining this project and you can raise the issues here. Please feel free to reach us at tartarus.iitg@gmail.com in case of any queries.
